upddate omn worflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -82,7 +82,7 @@ jobs:
             git config --global credential.helper store
             echo "https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com" > ~/.git-credentials
             chmod 600 ~/.git-credentials
-            cd /var/www/html/app/native_delight/client || { echo "Failed to cd to /home/fevico/app/native_delight/client"; exit 1; }
+            cd /var/www/html/app/native_delight/client || { echo "Failed to cd to /home/fevico/var/www/html/app/native_delight/client"; exit 1; }
             echo "Current directory: $(pwd)"
             git remote set-url origin https://github.com/Techevery/Native_Delight_Menu-Client.git
             git fetch origin || { echo "Git fetch failed"; exit 1; }
